// Per-leg ⓘ content for the live-tester panel (What / Why / How / Verify), keyed by
// the leg id used in legs.json. Source of truth: next-live-tester handoff
// 2026-06-20_09-42_live-tester-test-info-catalog-for-ui.md (poc/integration/src/live/*
// + README-*-journey.md, PR #649). The harness RUNS + records; it never declares
// PASS/FAIL — "verify" is the condition a leg colours GREEN on; the authoritative
// verdict is next-investigator's L3 raw-table recompute.

export interface LegInfo { what: string; why: string; how: string; verify: string }

export const LEG_INFO: Record<string, LegInfo> = {
  // ── SUITE A · ACT I — AUTH ─────────────────────────────────────────────
  'I.1': { what: 'A brand-new factor-less user must enrol a TOTP factor before it can act (AUTH-002).', why: 'An account with no second factor must NOT perform sensitive actions — enrolment is the gate that makes every later AAL2 session possible; skipping it = password-only access to money surfaces.', how: 'Provision a throwaway user → auth-login (expect enrolment-required) → /factors enrol TOTP → /challenge → /verify with a live TOTP code.', verify: 'Login signals enrolment-required AND the factor verifies (factor_verified=true).' },
  'I.2': { what: 'The real front door issues an MFA-elevated (AAL2) session for every seeded role/entity (AUTH-001/002).', why: 'Every privileged/money action rides an AAL2 bearer — if login→2FA→AAL2 does not actually elevate, the whole no-service_role-shortcut guarantee is hollow.', how: 'For each of 8 users: auth-login (password) → auth-2fa-verify (TOTP) → decode JWT claims, via the anon key (never service_role).', verify: 'At least 1 session carries aal=aal2; the SessionBook that drives Acts II/III is populated.' },
  'I.2b': { what: 'The real admin-portal login FORM works in a browser; the recorded video shows authenticated admin UI.', why: 'The API logins never touch the browser — without this the owner-facing clips would be blank and a broken portal login would go unnoticed.', how: 'Playwright drives the live admin-portal login form for the super-admin seed (U-SA).', verify: 'The tour completes; screenshots/video capture the authenticated portal.' },
  'I.3': { what: 'Each user sees ONLY the rows its tenant scope allows — RLS-authoritative (AUTH-003/004).', why: 'A client admin reading another tenant deposits is a data-leak/breach — isolation must hold at the read surface, not just the write path.', how: 'Per role, an authenticated tenant-read on deposits; check the client-admin (U-C1A) sees only its own client rows.', verify: 'U-C1A visible client_ids are all == C1.' },
  'I.4': { what: 'Low-privilege roles are denied privileged actions (AUTH-003 / ADMIN-004).', why: 'A viewer approving a deposit, or a CS unlocking a user, would be privilege-escalation — the role matrix must reject, not silently allow.', how: 'Viewer calls admin-deposit approve; CS calls admin-users-unlock — both with valid AAL2 bearers.', verify: 'Both return 403 permission_denied.' },
  'I.5': { what: 'Repeated bad logins lock the account; only a super-admin can unlock; login then restores (AUTH-005).', why: 'Brute-force protection + a controlled recovery path — no lockout = credential stuffing; no admin-only unlock = self-service bypass.', how: '6 wrong-password logins → super-admin admin-users-unlock → correct login.', verify: 'The 6th attempt is blocked AND the unlock returns 200 (post-unlock login restored).' },
  'I.6': { what: 'Machine-to-machine HMAC on the public deposits endpoint — valid accepted, forged rejected, per-client rate-limit observed (AUTH-006 / CLIENT-002).', why: 'The client wire is unauthenticated except by signature; a forged signature accepted = anyone mints deposits; no rate-limit = abuse.', how: 'Good HMAC create (expect 201); forged signature (v1=zeros, expect 401); a 12-burst counting 429s.', verify: 'good=201 AND forged=401 (rate-limit fail-open is counted, not required).' },
  'I.7': { what: 'Disable blocks login; enable restores; forgot-password does not leak account existence (AUTH-008/009/012).', why: 'Deactivation must actually bar access; and a forgot that answers differently for real vs unknown emails is an account-enumeration oracle.', how: 'admin-users-disable → login (blocked) → admin-users-enable → login (ok); auth-change-password forgot for an existing vs an absent email.', verify: 'disable=200, enable=200, login-while-disabled not 200, AND forgot(exists).status == forgot(absent).status (no leak).' },
  'I.8': { what: 'Exercises the step-up posture/verify EFs WITHOUT pretending a step-up-gated action exists (AUTH-007) — honest-limited.', why: 'AUTH-007 has ZERO deployed call-sites (Phase-2 deferred); claiming a green here would be false coverage — the test stays honest (always AMBER).', how: 'auth-step-up-posture + auth-step-up-verify with the super-admin session.', verify: 'AMBER by design (EFs exercised; no gated money-out to assert) — never a false GREEN.' },

  // ── SUITE A · ACT B — BANK-BOT seam ────────────────────────────────────
  'B.1': { what: 'A bot per-account credential is blast-radius-bounded to exactly one account (BBOT-002).', why: 'A key that can push statements for accounts it does not own could inject money rows into the wrong ledger.', how: 'Same key pushes to its OWN account (expect 2xx) then to a SIBLING account (expect reject).', verify: 'own < 300 AND cross-account >= 400 (403 bot_account_mismatch).' },
  'B.5': { what: 'Statement intake is idempotent via count-based dedup as the SOLE gate — no unique-index backstop (BBOT-001/005).', why: 'The bot re-scans + re-pushes the same rows every tick; without dedup that double-credits — and the design deliberately relies on count-dedup, not a DB unique constraint.', how: 'Feed an identical statement batch twice; read inserted each time.', verify: 'First push inserts >=1, second inserts 0.' },
  'B.10': { what: 'Only the bot that CLAIMED a withdrawal may finish (mark) it (BBOT-011 / F-BBOT-iv).', why: 'A foreign bot marking another claim could settle/fail a payout it never executed → money moved on a lie.', how: 'Create payout → claim with bot A → bot B tries to mark (expect 403) → bot A marks (expect 2xx).', verify: 'foreign mark >= 400 AND owner mark < 300.' },
  'B.10x': { what: 'The claimed→processing checkpoint, the approver processing view, and transfer-proof attachment (BBOT-011/012).', why: 'The maker/approver dual-control + proof trail is the audit spine of an outbound transfer; gaps here mean unprovable money-out.', how: 'claim → recordBankRefs (checkpoint) → fetchProcessing (approver sees it) → setTransferProof → mark success.', verify: 'checkpoint < 300 AND proof < 300 (item visible in processing).' },
  'B.8': { what: 'An OTP producer-write plane + per-account read plane, with info-leak collapse + cross-account isolation (BBOT-010).', why: 'OTPs gate transfers; a never-posted ref must not leak existence (404 not 200-empty), and one account must not read another OTP.', how: 'Post an OTP → read it back (same account) → read a never-posted ref → read with a different account key.', verify: 'post<300, OTP matches, never-posted=404, cross-account=403.' },
  'B.9': { what: 'Heartbeat with availability validation + balance update (BBOT-013).', why: 'The router uses availability + balance to pick banks; a bad availability accepted, or a balance not stamped, mis-routes real money.', how: 'heartbeat(online) → heartbeat(garbage availability) → updateBalance.', verify: 'heartbeat<300, bad-availability=400, balance<300.' },
  'B.3': { what: 'Credential rotate (new key works) + revoke (old key dies immediately) (BBOT-004 K1/K2).', why: 'Key rotation must not interrupt the bot, and a revoked key must be instantly dead — a lingering revoked key is a live credential leak.', how: 'push pre-rotate → rotate → push with new key → revoke → push with old key (on the maintenance bank, to spare scb).', verify: 'New key works after rotate AND post-revoke push = 401 (revoke mandatory).' },

  // ── SUITE A · ACT II — DEPOSIT ─────────────────────────────────────────
  'II.1': { what: 'A byte-identical replay returns the same deposit; same key + different body → conflict (DEPOSIT-001 / CLIENT-001 / ADR-11).', why: 'Clients retry on network blips — a retry that creates a SECOND deposit double-charges; a key reused for a different amount must be refused, not silently overwritten.', how: 'create → replay same key+body → replay same key + different amount.', verify: 'Replay returns the SAME id AND the conflict = 409.' },
  'II.2': { what: 'A fed statement auto-matches the deposit → wallet credit + MDR split across partners, two profiles A/B (DEPOSIT-002 / WALLET-003/007).', why: 'The core money-in path; a missed match = customer paid but not credited; a wrong MDR split = partners mis-paid; conservation must be satang-exact.', how: 'create → feed an in-statement of the amount → poll until paid; read change-logs (credit / mdr_distribute / mdr_skip).', verify: 'status=paid AND exactly 1 deposit_credit; L3 recount NET + Σpartner + residual = gross, satang-exact.' },
  'II.3': { what: 'Manual slip upload → verify-now (genuine) → 6-check approve, driven through the real /deposit portal UI (DEPOSIT-004/007/008).', why: 'The manual lane is what staff use for slip deposits; the UI itself must work end-to-end (not just the EF), or operators cannot finalize.', how: 'admin (U-SA) drives uploadSlip/verifyNowGenuine/approveToPaid via Playwright (EF fallback if a UI step fails).', verify: 'GREEN only if paid AND all three steps were UI-driven; AMBER if paid via an API fallback (flag to harden the UI).' },
  'II.3b': { what: 'Approving a slip whose receiver does not match must BLOCK → no credit (DEPOSIT-007, V2 receiver-mismatch).', why: 'The V2 receiver gate is anti-fraud — if a mismatched receiver still finalizes, forged-slip deposits get credited (direct money loss).', how: 'genuine slip → approve with a slip_receiver_proxy whose last-4 matches no real account.', verify: 'approve >= 400 (V2_FRAUD), status not paid, 0 deposit_credit.' },
  'II.3c': { what: 'A forged verify verdict must not silently finalize the deposit (DEPOSIT-008 negative).', why: 'A forged slip flagged by verification must never become paid — money-safety on the fraud signal.', how: 'verify-now thunder_verdict=forged (→ checking) → approve with a clean proxy (forged isolated as the only signal).', verify: 'forged recorded (200, verdict=forged) AND money-safe (not paid, 0 credit).' },
  'II.4': { what: 'The AU1 upload-gate refuses a mismatched slip unless an audited force-approve override is supplied (DEPOSIT-009).', why: 'Overrides must be deliberate + audited — a silent bypass removes the human-accountability trail on a risky approve.', how: 'upload a mismatched slip without the marker (expect 409) then with force_approve (expect 200 + override_audit_id).', verify: 'no-marker = 409 AU1_REFUSED AND with-marker < 300 carrying an override_audit_id.' },
  'II.5': { what: 'Two same-amount deposits across clients + one ambiguous statement → refuse-to-guess, park for admin (DEPOSIT-005).', why: 'A statement carries no client identity; guessing which client owns the money = mis-credit; parking is the money-safe answer.', how: 'two same-amount deposits (C1, C2) → feed one ambiguous in-statement → check neither credited.', verify: 'Both deposits have 0 deposit_credit (parked for admin-deposit-resolve).' },
  'II.6': { what: 'A pending, slip-less deposit past its deadline → expired + deposit.expired callback, no credit (DEPOSIT-003 / CALLBACK-004).', why: 'Stale deposits must close (not linger claimable) and the merchant must be told — without expiry, abandoned deposits could later be matched/credited wrongly.', how: 'backdate expires_at → run sweep_expired_deposits → poll until expired.', verify: 'status=expired AND 0 deposit_credit (expired callback queued).' },
  'II.7': { what: 'A client self-cancels its OWN pending deposit via an AAL2 session; idempotent; cross-tenant blocked (DEPOSIT-010).', why: 'Clients need self-service cancel, but only via a logged-in session (not the machine key), only their own, and a re-cancel must not move money or fire callbacks.', how: 'deposits-cancel with the client AAL2 bearer → re-cancel → cancel a slip-present + a terminal deposit → cross-tenant attempt.', verify: 'cancel=200→cancelled, idempotent (cancelled_at stable), 0 callback/credit, SLIP_PRESENT/NOT_PENDING=409, cross-tenant=403.' },
  'II.8': { what: 'Tenant-scoped deposit reads + the wallet triple (balance/frozen/available) + partner wallet (DEPOSIT-013 / WALLET-001/002/006 / AUTH-004).', why: 'Dashboards depend on correct scoped reads + an accurate available-balance (= balance − frozen); a wrong triple misleads withdrawal decisions.', how: 'per role tenant-read deposits; read the client wallet triple + a partner wallet.', verify: 'The wallet triple resolves (balance/frozen/available consistent).' },
  'II.9': { what: 'Resending a callback makes no state change and creates no new credit (DEPOSIT-012 / CALLBACK-005).', why: 'Merchants re-request callbacks; a resend that re-credits or re-finalizes is a money-duplication bug (§9 invariant 4).', how: 'count credits → deposit-resend-callback on the golden deposit → count again.', verify: 'resend < 500 AND deposit_credit unchanged.' },
  'II.9b': { what: 'Every callback is well-formed + signed, carries a stable dedup identity, and re-signs per attempt (CALLBACK-002 / WC1/WC8/WC10).', why: 'Merchants verify the signature + dedup on event-id; a malformed/unsigned/duplicate-id callback breaks their integration or double-processes.', how: 'read the paid callback rows + attempts; trigger a resend; check signatures + identity stability.', verify: 'One stable event_id+dedup_key, resend reuses it, every attempt signature well-formed (+ distinct per attempt).' },
  // DEPOSIT enforcement (II.E*)
  'II.E1': { what: 'Per-bank deposit amount band: deposit_min_amount / maximum_deposit_amount (DEPOSIT-001 AC#8).', why: 'Admin-configurable bank settings are only worth anything if the create path actually ENFORCES them — a no-op gate silently accepts what it should block.', how: 'set band [5000,9000]; create below / above / in-band.', verify: 'below & above = 400 AMOUNT_OUT_OF_RANGE / 0 rows; in-band = 201 / 1 row.' },
  'II.E2': { what: 'Per-bank daily cap (maximum_number_of_deposits) + BKK-midnight lazy reset (DEPOSIT-001 AC#5/#7).', why: 'A daily cap that does not reset, or does not enforce, mis-states bank capacity and lets through over-cap money.', how: 'cap=2, fill it, hit it; back-date the reset epoch, retry.', verify: '#1/#2=201, #3=503 NO_BANK_AVAILABLE / 0 rows, #4 (after back-dated reset)=201 / 1 row.' },
  'II.E3': { what: 'The bank deposit maintenance window filters it out of the pool (DEPOSIT-001 D1-12).', why: 'A bank in maintenance must not receive deposits; a window that does not exclude it routes money to a closed bank.', how: 'window covering now → create; window moved to the past → create.', verify: 'in-window=503 NO_BANK_AVAILABLE / 0 rows; out-of-window=201 / 1 row.' },
  'II.E4': { what: 'The per-client deposit switch enable_deposit (DEPOSIT-001 D1-10).', why: 'A disabled client must not be able to deposit; a no-op switch silently accepts.', how: 'set enable_deposit=false, create; restore, create.', verify: 'disabled=403 DEPOSIT_DISABLED_FOR_CLIENT / 0 rows; re-enabled=201 / 1 row.' },
  'II.E5': { what: 'The global app_settings.deposit_maintenance kill-switch (DEPOSIT-001 D1-11).', why: 'The global stop must actually stop every deposit; a no-op kill-switch is a false safety control.', how: 'set on, create; clear, create.', verify: 'on=503 DEPOSIT_MAINTENANCE / 0 rows; cleared=201 / 1 row.' },
  // DEPOSIT woven faults
  'F-DEP-i': { what: 'Re-approving an already-paid deposit must not double-credit (dup-credit guard).', why: 'Direct money duplication if a paid deposit can be finalized twice.', how: 're-approve the golden deposit; count credits.', verify: 'refused/idempotent AND exactly one deposit_credit (dup-credit=0).' },
  'F-DEP-ii': { what: 'A flaky merchant endpoint must be RETRIED then delivered exactly once (at-least-once, dup-egress=0).', why: 'Not dropped, not duplicated — a callback that double-delivers double-processes the merchant.', how: 'point the endpoint at a 500-once→200 receiver; trigger; observe attempts.', verify: 'attempt_count>=2 + merchant saw >=2 POSTs + ONE callback_queue row + ONE credit.' },
  'F-DEP-iii': { what: 'Callbacks that exhaust retries dead-letter AND raise the P2.12 must-page alert.', why: 'No-alerts must never silently mean alerts-dead — an unraised dead-letter is invisible money loss.', how: 'point at an always-500 receiver → 3×500 → dead_letter → fingerprint → #mb-alerts-p2.', verify: 'dead_letter within 15 min + fingerprint (GREEN if Keep-confirmed, else AMBER condition-met).' },

  // ── SUITE A · ACT III — PAYOUT ─────────────────────────────────────────
  'III.1': { what: 'Creating a payout freezes GROSS in the client wallet; an over-amount is rejected (PAYOUT-001).', why: 'Funds must be reserved at create (so balance cannot be double-spent), and an unaffordable payout must never enter the queue.', how: 'snapshot wallet → create 1000 → re-read → create 999,999,999.', verify: 'frozen up by gross AND over-amount >= 400.' },
  'III.2': { what: 'Bot claims + marks success → wallet debited, MDR distributed, success callback (PAYOUT-002 / WALLET-003).', why: 'The money-out happy path; a settle that does not debit = money left the bank but not the ledger.', how: 'create → bot claim → mark success → read settle/mdr/callbacks.', verify: 'status=success, 1 payout_settle, 1 payout.success callback.' },
  'III.3': { what: 'Bot marks failed → NO debit, freeze released, failed callback (PAYOUT-003).', why: 'A failed transfer must return the frozen funds — a fail that still debits steals from the client.', how: 'snapshot → create → mark failed (bank_timeout) → re-read.', verify: 'status=failed AND debit=0 (1 payout_unfreeze, balance restored).' },
  'III.4': { what: 'A review-state payout is resolved by admin reconcile to success OR failed; review sends no premature callback (PAYOUT-004).', why: 'Stuck payouts need a deterministic admin resolution, and a premature callback on review would mislead the merchant.', how: 'two payouts → both review → admin reconcile one→success, one→failed.', verify: 'outcome A=success, B=failed.' },
  'III.5': { what: 'A review payout is driven to success by a matching bank out-debit (system, not a human), matched by request_id (PAYOUT-009 / MATCH-003).', why: 'The bank statement is the ground truth of money leaving — it must settle a payout without a human, matched on the PAY-token.', how: 'create with a PAY-prefixed reqId → feed an out-statement → poll sweep_payout_reconcile.', verify: 'status=success (statement matched, matched_link_step=payout_reconcile).' },
  'III.6': { what: 'Admin cancels a still-pending payout → cancelled, freeze released, one cancelled callback (PAYOUT-005).', why: 'Ops must be able to pull back a not-yet-claimed payout and the funds must unfreeze.', how: 'create (no bot claim) → admin-payout-cancel.', verify: 'status=cancelled.' },
  'III.7': { what: 'A pending payout auto-cancels on stale timeout (flag-gated) and on bank maintenance, freeze released (PAYOUT-008/010).', why: 'Payouts must not hang forever, and a bank in maintenance cannot execute — both must release funds, with distinct reasons.', how: 'stale: backdate + enable flag → sweep_stale_payouts; maint: payout into the maintenance bank → sweep_payouts_bank_maintenance.', verify: 'Both status=cancelled (distinct failure reasons).' },
  'III.8': { what: 'Admin corrects a failed/review payout to success; ends as a clean success — one settle, one MDR (PAYOUT-012 / WALLET-003).', why: 'A transfer the bank actually completed but the system marked failed must be correctable to truth — without double-paying.', how: 'mark failed → admin-payout-correct → read settle/mdr/wallet.', verify: 'status=success (re-freeze-then-settle nets a clean single debit; MDR once).' },
  'III.9': { what: 'Reverse a settled payout → failed, MDR clawed back, conservation closes (PAYOUT-013 / WALLET-008).', why: 'A settled payout later found bad must fully unwind — partner MDR clawed back, client recredited, no value created/destroyed.', how: 'success → admin-payout-reverse-settle → sum clawback/shortfall/recredit.', verify: 'status=failed AND |Σclawback + Σshortfall − fee| < 0.005 (satang conservation).' },
  'III.10': { what: 'Resending a payout callback moves no money; payout reads are tenant-scoped (PAYOUT-007 / AUTH-004).', why: 'Idempotent callback resend (no second debit) + correct per-tenant payout visibility.', how: 'success → count settle → payout-resend-callback → count again; per-role tenant-read payouts.', verify: 'resend < 500 AND settle count unchanged.' },
  'III.11': { what: 'After a full create→claim→settle→reverse cycle, every wallet returns to its EXACT pre-create satang.', why: 'The epic-seal money invariant — a complete round-trip must be value-neutral across ALL wallets (no leak anywhere).', how: 'snapshot all wallets → run the cycle → snapshot again → diff.', verify: 'Zero wallets drifted.' },
  // PAYOUT enforcement (III.E*)
  'III.E1': { what: 'The per-client payout switch enable_payout (PAYOUT-001 AC#5).', why: 'A disabled client must not be able to withdraw.', how: 'enable_payout=false create (reject) → restore → create (accept).', verify: 'disabled=4xx PAYOUT_DISABLED / 0 rows; re-enabled accepted / 1 row.' },
  'III.E2': { what: 'The per-client minimum payout min_payout lower boundary (PAYOUT-001 AC#9).', why: 'Below-minimum withdrawals must be refused before any freeze.', how: 'min_payout=500; create 499 (reject) → 500 (accept).', verify: 'below=400 AMOUNT_OUT_OF_RANGE / 0 rows; at-min accepted / 1 row.' },
  'III.E3': { what: 'The router routes a pool payout ONLY to an online bank, excluding an offline one — even when offline is the LRU favourite (ADR-30 AC-1).', why: 'Routing money to an offline bank = a stuck/failed transfer; availability must override LRU, or the fair router sends work to a dead bank.', how: '2-bank pool; make the LRU-favourite OFFLINE + the loser ONLINE; create a Mode-1 pool payout; read the assigned bank. Both directions.', verify: 'Both directions route to the ONLINE bank (AMBER if it picks the offline favourite = no-op gate; BLOCKED if neither routes). AC-2 stale-heartbeat / AC-3 withdrawal-band not yet live.' },
  // PAYOUT woven faults
  'F-PAY-i': { what: 'Reversing an already-reversed payout must be blocked with no second money move (double-reverse blocked).', why: 'Fail-safe dedup — a second reverse would move money twice.', how: 'reverse once → reverse again; count reverse rows.', verify: '2nd reverse >= 400 AND reverse rows unchanged (exactly 1).' },
  'F-PAY-ii': { what: 'When an MDR recipient cannot cover its clawback, log an audit-only shortfall — never force a wallet negative (conservation still closes).', why: 'A forced-negative wallet is corruption; the shortfall must be recorded, not papered over.', how: 'drain recipient wallets below their share → reverse.', verify: 'reverse < 400 + >=1 mdr_unwind_shortfall + NO wallet negative.' },
  'F-PAY-iii': { what: 'The P2.16 (false-success) / P2.17 (false-failed) operator alerts catch III.8/III.9 mis-states (MONITOR-003).', why: 'These alerts are the signal that a correction/reverse mis-state gets caught; silent = undetected money mis-state.', how: 'exercised via III.8 + III.9; confirm via Keep if KEEP_ALERTS_API set.', verify: 'GREEN only when Keep confirms p2.16/p2.17 (else AMBER; #mb-alerts-p2 is the surface).' },

  // ── SUITE A · ACT MT / KTB ─────────────────────────────────────────────
  'MT.1': { what: 'A sub-client (SC1) runs a full deposit→payout lane within scope (AUTH-004).', why: 'Tenancy depth — money must flow correctly for sub-clients, not just the primary C1.', how: 'deposit via slip (2200) → paid; payout (800) claim→settle.', verify: 'deposit paid (1 credit) AND payout success (1 settle).' },
  'MT.2': { what: 'A second client (C2) of the same merchant runs a full deposit→payout lane within scope (AUTH-004).', why: 'Tenancy depth — money must flow correctly for sibling clients.', how: 'deposit via slip (2200) → paid; payout (800) claim→settle.', verify: 'deposit paid (1 credit) AND payout success (1 settle).' },
  'MT.3': { what: 'Two clients creating deposits CONCURRENTLY stay isolated (AUTH-004).', why: 'A race must not cross-contaminate ids/amounts/ownership — concurrency bugs leak one tenant money into another row.', how: 'Promise.all create C1@313 + C2@314 → read both.', verify: 'distinct ids, amounts 313/314 not crossed, each row owned by its creator.' },
  'K.1': { what: 'A deposit on the KTB bank routes to KTB, a fed ktb statement auto-matches, credits once (BBOT-006 / MATCH-001 on ktb).', why: 'Proves the match/credit path is bank-dialect-agnostic — KTB is not a special-case that silently breaks.', how: 'KTB client create → confirm routed to KTB → feed a ktb in-statement → poll until paid.', verify: 'routed_to_ktb AND paid AND exactly 1 credit.' },
  'K.2': { what: 'The payout claim→transfer→settle lane works on the KTB bank (BBOT-011 on ktb).', why: 'Outbound money-out must also work on the second bank, including its single-control topology.', how: 'create→claim→mark-success on ktb → read settle/callback.', verify: 'status=success, 1 settle, 1 payout.success.' },

  // ── SUITE B — Automatch (real deployed bot scraping the portal) ─────────
  'L1f': { what: 'N deposits coexist as unmatched rows then each auto-matches, credits once, no cross-match.', why: 'Stresses the matcher under concurrency — proves no double-credit / no cross-match when many are pending.', how: 'create N-1 + inject all → assert per-item paid/1-credit/1-stmt/own-amount (size = DEPOSIT_COUNT).', verify: 'all paid, each credited once, one stmt row each, no cross-match.' },
  'L1g': { what: 'Cross-client ambiguity → review, neither credited (= A II.5 multi-candidate park).', why: 'A statement carries no client identity; guessing = mis-credit; parking is money-safe.', how: 'two same-amount cross-client deposits → inject one ambiguous statement.', verify: 'match_status=review, both uncredited, 0 callback.' },
  'L1g2': { what: 'Same-client same-amount ambiguity → auto-pick the OLDEST, no park (degenerate FIFO).', why: 'The sealed §FA1 carve-out — a single customer repeat transfers must FIFO-resolve, not park forever.', how: 'OLD then NEW deposit → inject one → expect matched.', verify: 'matched (not review), oldest won, old paid/1-credit, new pending/0.' },
  'L1h': { what: 'Slip-less deposit past deadline → expired + callback, no credit (= A II.6).', why: 'Stale deposits must close and the merchant be told.', how: 'backdate deadline → sweep → poll.', verify: 'expired, 0 credit.' },
  'L1m': { what: 'Replay returns the same deposit id; key-reuse with a different body = 409 (= A II.1 idempotency).', why: 'Retries must not double-create; a reused key for a different amount must be refused.', how: 'create → replay same → replay different body.', verify: 'same id on replay, 409 on key-reuse-different-body.' },
  'L1j': { what: 'AAL2 client self-cancel, idempotent, callback-silent, no wallet move, cross-tenant 403 (= A II.7).', why: 'Self-service cancel only via a logged-in session, only own, re-cancel moves no money.', how: 'deposits-cancel with the client AAL2 bearer → re-cancel → cross-tenant attempt.', verify: '200→cancelled + idempotent + 0 cb/credit + 403 cross-tenant.' },
  'L1n': { what: '2-profile MDR split, satang-exact conservation (= A II.2 MDR fan-out).', why: 'A wrong MDR split mis-pays partners; conservation must be satang-exact.', how: 'paid deposit → read mdr change-logs per profile.', verify: 'paid + NET+Σmdr+residual = gross (satang-exact) per profile.' },
  'L1i': { what: 'Every callback well-formed + per-attempt-distinct + merchant-dedup id (= A II.9b callback signature).', why: 'Merchants verify signature + dedup; malformed/duplicate-id breaks integrations.', how: 'read paid callback rows + attempts.', verify: 'all signed, distinct per attempt, every row has a dedup id.' },
  'L4': { what: 'A single payout driven 100% by the deployed bot: claim→OTP→transfer→re-scrape→reconcile→callback.', why: 'Proves the FULL real-bot OUT lane, no harness shortcut.', how: 'create→bot claims→portal auto-generates the out-row→bot re-scrapes→reconcile→success callback.', verify: 'claimed + out-row scraped + settled + payout.success (SUPERSEDED by L4b when WITHDRAW_COUNT>=2).' },
  'L4b': { what: 'M payouts claimed as ONE batch (single batch_id), maker-per-item + one OTP approval, M out-rows reconciled.', why: 'The real batch behaviour ops rely on; proves one-batch-per-bank + per-item settle.', how: 'create M back-to-back→bot batch-claim→settle all→M callbacks (size = WITHDRAW_COUNT).', verify: 'created M, claimed M (single batch_id), out-rows M, settled M, M payout.success.' },
  'L4f': { what: 'Stale payout → sweep cancel, freeze released, no debit (= A III.7 stale).', why: 'Payouts must not hang forever; funds must unfreeze.', how: 'backdate + sweep_stale_payouts.', verify: 'cancelled, freeze released, debit=0, 1 cancelled callback.' },
  'L4m': { what: 'Bank-maintenance cancel — §ADR-9 code in callback payload (= A III.7 maint).', why: 'A bank in maintenance cannot execute; funds must unfreeze with the right reason.', how: 'payout into the maintenance bank → sweep_payouts_bank_maintenance.', verify: 'cancelled via maintenance path, freeze released, debit=0.' },
  'L4k': { what: 'Replay returns the same payout; freeze applied ONCE (= A III.10 idempotency).', why: 'A re-created payout must not double-freeze the client wallet.', how: 'create → replay same → conflict variant.', verify: 'same payout on replay, 1 freeze row (not doubled), 409 on conflict.' },
  'L2c': { what: 'A 2nd deposit bound to a failing callback → dead_letter → P2.12 page (= A F-DEP-iii).', why: 'Closes the silent-dead-letter gap; deposit #1 must stay pristine.', how: 'bind a deposit to an always-500 receiver (CALLBACK_FAIL_PATH) → exhaust retries.', verify: 'dead_letter + fingerprint to #mb-alerts-p2 (deposit #1 unchanged).' },
  'L3': { what: 'Rotate the bot credential mid-journey with overlap; the retiring key stays green for a tick, the new pair works.', why: 'Zero-downtime key rotation in production.', how: 'rotate(overlap) → probe crosses on retiring key → swap (opt-in ROTATE_STRETCH).', verify: 'overlap probe lands + swap green.' },

  // ── SUITE C — Restart (the only suite that restarts the bot) ────────────
  'C.L2a': { what: 'SP3 crash-restart dedup — restart the STMT bot; R survives, the fresh bot re-scrapes it, count-dedup collapses the re-push.', why: 'A bot crash+restart must NOT re-credit a surviving row — the real-world failure steady-state L2a cannot fully prove.', how: 'restart via SIGKILL/BOT_RESTART_CMD → wait → measure.', verify: 'R survived (no portal bounce) AND bank_statements count + credit + callbacks unchanged (dup-credit=0).' },
  'C.P1': { what: 'III.5 over a real restart — orphan a claim by restarting the payout bot, age it, sweep to review, then a matching out-debit settles it.', why: 'A bot that dies mid-claim must leave a recoverable (not lost, not double-paid) payout.', how: 'claim→BOT_RESTART_CMD orphan→backdate claimed_at→sweep_stale_claims→review→match_payout_statement.', verify: 'payout review→success, statement matched_link_step=payout_reconcile.' },
  'C.P2': { what: 'A mismatched out-debit (|diff|>50 THB) → amount_mismatch, payout STAYS review (never auto-fails).', why: 'The bank moved a different amount than expected — the system must flag, not silently fail/settle.', how: 'inject an out-debit off by >50 → match_payout_statement.', verify: 'outcome=amount_mismatch AND payout stays review (mark_success NOT called).' },

  // ── SUITE D — Fair-router (LRU distribution across a fleet) ─────────────
  'FRD1': { what: 'Deposit LRU distribution — N deposits assigned with spread <= 1, all in-fleet, Σ=N.', why: 'Fair must mean even — a skewed router overloads one account (cap/limits) and starves others.', how: 'create N → read each system_bank_account_id.', verify: 'spread <= 1, all assigned in-fleet, count conserved.' },
  'FRD2': { what: 'Each deposit matches→paid via the per-account (login-scoped) scrape, credited once.', why: 'Distribution is useless if the per-account bot cannot then match its own slice.', how: 'per-account inject → real bot scrapes its login → poll paid.', verify: 'all paid, credited exactly once.' },
  'FRD2cb': { what: 'Per-account the deposit.paid callback actually DELIVERED (not dead-letter) + merchant received it.', why: 'Closes the silent-dead-letter gap — a per-account callback misconfig would dead-letter while the lane still shows paid.', how: 'stand up a receiver, repoint the client endpoint, assert delivery per account.', verify: 'callback_queue.status=delivered + merchant receipt per account (BLOCKED without the receiver seam).' },
  'FRD3': { what: 'Isolation — no cross-account match + no foreign amount in any account portal slice.', why: 'Per-login isolation is the security boundary of the shared portal; a leak = one account seeing/matching another statements.', how: 'check matched-statement system_bank_id + each slice amounts.', verify: 'every matched stmt carries its OWN account id + no foreign amount in any slice.' },
  'FRP1': { what: 'Payout LRU distribution — N Mode-1 (pool) payouts routed with spread <= 1, all in-fleet.', why: 'Outbound fairness — even payout load across the fleet via the webhook router.', how: 'create N Mode-1 → poll each required_bank_account_id.', verify: 'spread <= 1, all routed in-fleet.' },
  'FRP2': { what: 'Exactly-once claim + per-bank batch isolation — every row claimed_by == its routed bank, one batch_id per bank, no batch spans two banks.', why: 'A claim crossing banks, or a row claimed by the wrong bank, would execute money on the wrong account.', how: 'claim_withdrawal_items per account (drive) or observe the real bots.', verify: 'all claimed by the routed bank, distinct batch_id per bank, no cross-bank batch.' },
  'FRP3': { what: 'Per-account the payout.success callback DELIVERED.', why: 'Same silent-dead-letter gap for the OUT lane.', how: 'GATED — honest-SKIP in plain drive (rows never settle); asserts under FAIRROUTER_CLAIM=observe or FAIRROUTER_FORCE_SETTLE=1.', verify: 'callback_queue.status=delivered + merchant receipt per account (SKIP if not settled).' },
  'FRX': { what: 'Cross-bank method gate (SCB+KTB) — no deposit routes to a payout-only bank; payouts include it.', why: 'Mixing banks with asymmetric methods must respect the method gate, or deposits land on a bank that cannot accept them.', how: 'under FAIRROUTER_CROSSBANK=1 with a KTB payout-only account.', verify: 'deposit lane excludes KTB; payout lane includes it (method gate both ways).' },

  // ── SUITE DEP — Deposit golden (standalone DEPOSIT+AUTH) ────────────────
  'DEP.all': { what: 'Standalone DEPOSIT+AUTH golden path: L0 readiness → login→2FA→AAL2 → client QR create → admin slip upload→verify→approve→paid+MDR+callback → dup-credit/dup-egress/dead-letter faults.', why: 'The manual money-in path end-to-end on sinuw, a subset of A ACT I+II; owner-gated (OWNER_GO_LIVE_DEPOSIT) else DRY-VALIDATE.', how: 'run-live-deposit.sh: L0 → L1-auth → L1-create → L1-slip/verify → L1-approve/callback → F-i/F-ii/F-iii.', verify: 'AAL2 minted, 201 pending, paid+credited+callback delivered; dup-credit=0, callback delivered once, dead-letter pages P2.12.' },
};

// Which leg id(s) each panel control documents, keyed by `${suiteId}:${env}` (the
// same env var can mean different things per suite — e.g. OWNER_GO_LIVE_DEPOSIT is
// Suite A's deposit ACT but Suite DEP's whole run-gate). Epic toggles list their
// whole act; skip-flags map to the one leg they gate. A control absent here has no ⓘ.
export const CONTROL_LEGS: Record<string, string[]> = {
  // Suite A — epic toggles list their whole act (+ woven faults)
  'A:OWNER_GO_LIVE_AUTH': ['I.1', 'I.2', 'I.2b', 'I.3', 'I.4', 'I.5', 'I.6', 'I.7', 'I.8'],
  'A:OWNER_GO_LIVE_BBOT': ['B.1', 'B.5', 'B.10', 'B.10x', 'B.8', 'B.9', 'B.3'],
  'A:OWNER_GO_LIVE_DEPOSIT': ['II.1', 'II.2', 'II.3', 'II.3b', 'II.3c', 'II.4', 'II.5', 'II.6', 'II.7', 'II.8', 'II.9', 'II.9b', 'F-DEP-i', 'F-DEP-ii', 'F-DEP-iii'],
  'A:OWNER_GO_LIVE_PAYOUT': ['III.1', 'III.2', 'III.3', 'III.4', 'III.5', 'III.6', 'III.7', 'III.8', 'III.9', 'III.10', 'III.11', 'F-PAY-i', 'F-PAY-ii', 'F-PAY-iii'],
  'A:OWNER_GO_LIVE_MT': ['MT.1', 'MT.2', 'MT.3'],
  'A:OWNER_GO_LIVE_KTB': ['K.1', 'K.2'],
  'A:OWNER_GO_LIVE_ENFORCE': ['II.E1', 'II.E2', 'II.E3', 'II.E4', 'II.E5', 'III.E1', 'III.E2', 'III.E3'],
  // Suite B — skip-flags → the leg they gate
  'B:SKIP_PARK': ['L1g'], 'B:SKIP_DEGEN': ['L1g2'], 'B:SKIP_EXPIRE': ['L1h'], 'B:SKIP_DEP_IDEM': ['L1m'],
  'B:SKIP_DEP_CANCEL': ['L1j'], 'B:SKIP_MDR': ['L1n'], 'B:SKIP_CBSIG': ['L1i'], 'B:SKIP_WITHDRAW': ['L4', 'L4b'],
  'B:SKIP_STALE': ['L4f'], 'B:SKIP_MAINT': ['L4m'], 'B:SKIP_PAY_IDEM': ['L4k'], 'B:SKIP_DEADLETTER': ['L2c'],
  'B:DEPOSIT_COUNT': ['L1f'], 'B:WITHDRAW_COUNT': ['L4b'], 'B:ROTATE_STRETCH': ['L3'],
  // Suite C
  'C:SKIP_DUPFAULT': ['C.L2a'], 'C:SKIP_RECONCILE': ['C.P1', 'C.P2'],
  // Suite D
  'D:FAIRROUTER_N': ['FRD1', 'FRP1'], 'D:FAIRROUTER_FORCE_SETTLE': ['FRP3'], 'D:FAIRROUTER_CROSSBANK': ['FRX'],
  'D:SKIP_DEPOSIT': ['FRD1', 'FRD2', 'FRD2cb', 'FRD3'], 'D:SKIP_PAYOUT': ['FRP1', 'FRP2', 'FRP3'],
  // Suite DEP
  'DEP:OWNER_GO_LIVE_DEPOSIT': ['DEP.all'],
};

// Resolve a (suite, control env) → its ordered list of {id, ...info} blocks (or []).
export function infoForControl(suiteId: string, env: string): Array<LegInfo & { id: string }> {
  return (CONTROL_LEGS[`${suiteId}:${env}`] || []).map((id) => ({ id, ...(LEG_INFO[id] || { what: '', why: '', how: '', verify: '' }) }));
}
