// The live-tester menu is driven by the test team's catalog JSON (the deliverable
// for "the UI auto-runner"): docs/requirements/live-test-journey-v2-catalog.json in
// the gateway repo. Each card carries its own run recipe (exec.command, owner-go
// gate, speed, runnable flag), so the menu always mirrors the revised v2 journey —
// nothing is hardcoded here. Regenerated by build-live-catalog.py from the v2 doc.
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const CATALOG_REL = 'docs/requirements/live-test-journey-v2-catalog.json';

// kept for client type compatibility (cards carry no per-run controls anymore)
export type ControlType = 'toggle' | 'number' | 'text' | 'select';
export interface Control { env: string; label: string; type: ControlType; def?: string; options?: string[]; help?: string; danger?: boolean }

export interface Suite {
  id: string; label: string; title: string;
  command: string;            // exec.command — run from <root>/poc/integration
  speed: string;              // FAST | SLOW | OTHER
  epic?: string; state?: string; result?: string | null;
  runnable: boolean; reason?: string;          // not_runnable_reason
  ownerGated?: boolean; ownerGoEnv?: string;   // moves real money/bot
  optionalEnv?: { name: string; description?: string }[];
  cast?: string;
  controls: Control[];        // always [] (kept so the client type is unchanged)
}

interface CatalogCard {
  id: string; title?: string; epic?: string; speed?: string; state?: string; result?: string | null;
  runnable?: boolean; not_runnable_reason?: string; requires_owner_go?: boolean; owner_go_env?: string; cast?: string;
  exec?: { command?: string | null; optional_env?: { name: string; description?: string }[] };
}

function mapCard(c: CatalogCard): Suite {
  return {
    id: c.id, title: c.title || c.id, label: `${c.id} · ${c.title || ''}`.trim(),
    command: c.exec?.command || '', speed: c.speed || 'OTHER',
    epic: c.epic, state: c.state, result: c.result ?? null,
    runnable: !!c.runnable, reason: c.not_runnable_reason || '',
    ownerGated: !!c.requires_owner_go, ownerGoEnv: c.owner_go_env || undefined,
    optionalEnv: c.exec?.optional_env ?? [],
    cast: c.cast,
    controls: [],
  };
}

export interface Catalog { suites: Suite[]; summary: unknown; root: string | null }

function readCatalogAt(root: string): Catalog | null {
  const f = join(root, CATALOG_REL);
  if (!existsSync(f)) return null;
  try {
    const j = JSON.parse(readFileSync(f, 'utf8'));
    const cards = Array.isArray(j?.cards) ? (j.cards as CatalogCard[]) : [];
    return { suites: cards.map(mapCard), summary: j?.summary ?? null, root };
  } catch { return null; }
}

/** First candidate repo root that has a readable catalog wins (agent worktree →
 *  primary checkout). Returns root so the run executes against the SAME checkout. */
export function loadCatalog(roots: string[]): Catalog {
  for (const r of roots) { const c = readCatalogAt(r); if (c) return c; }
  return { suites: [], summary: null, root: null };
}
